name: Unit Test Workflow

on:
  pull_request:
    branches:
      - develop
      - release/*
      - hotfix/*
  push:
    branches:
      - BRDY*

jobs:
  test:
    name: Unit Tests

    runs-on: ubuntu-18.04

    steps:
      - name: Clone Repo
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit tests
        run: ./gradlew app:test --stacktrace
